# Project: Dev-demo
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../5-b17-sub/5-b17-main.o ../5-b17-sub/5-b17-sub.o
LINKOBJ  = ../5-b17-sub/5-b17-main.o ../5-b17-sub/5-b17-sub.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Dev-demo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../5-b17-sub/5-b17-main.o: ../5-b17-sub/5-b17-main.cpp
	$(CPP) -c ../5-b17-sub/5-b17-main.cpp -o ../5-b17-sub/5-b17-main.o $(CXXFLAGS)

../5-b17-sub/5-b17-sub.o: ../5-b17-sub/5-b17-sub.cpp
	$(CPP) -c ../5-b17-sub/5-b17-sub.cpp -o ../5-b17-sub/5-b17-sub.o $(CXXFLAGS)
